### ISSUE TITLE
Is this repo really needed?

### ISSUE THREAD

**Issue by fulalas** [pop-os/network-manager-applet#1]
Does COSMIC really require `network-manager-applet`? If so, is it possible to just use the [official repo](https://gitlab.gnome.org/GNOME/network-manager-applet)?

I'm asking because I'm testing COSMIC on PorteuX distro (Slackware based) and although the network applet shows in the panel, it doesn't do anything so I can't see any wifi network available, etc.

**Comment by mmstick** [comment]
This contains a downstream patch for disabling the app tray icon in COSMIC.
https://github.com/pop-os/network-manager-applet/commit/8af78f7ebfa770f24cf46693cb215c5c22dbacfb

**Comment by fulalas** [comment]
Yeah, I saw that. I'm just wondering if GNOME `network-manager-applet` is really needed since COSMIC has its own.

**Comment by mmstick** [comment]
The package built from this is called `network-manager-gnome`, and this provides the "Advanced Network Configuration" app, which is required for the COSMIC Alpha. We don't have advanced network settings implemented yet.

**Comment by fulalas** [comment]
I see, thanks.

It's odd that even with that I can't make COSMIC network applet work. :(
